name = "test-fpm"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "Copyright 2021, Jane Doe"

[library]
source-dir="src"

[[ executable ]]
name="main"
source-dir="app"
main="main.f90"

[build]
link = ["blas", "lapack"]
auto-executables = true
auto-tests = true
auto-examples = true
